import journal from '@/data/journal.json';
import assets from '@/data/assets.json';

// The Journal (docs/design/phase-c4-1b-journal.md). Two voices, kept apart in the data and on the page:
// `morph` is Morph's own wording, quoted with its source (data/journal.json, generated by `npm run journal`);
// everything written here is the concept's: labels, summaries of verified facts, dated notes, captions, alt text.
// Morph articles are not reproduced: the page quotes a short excerpt and links to the full text on morphparfum.ro.

type Source = (typeof journal.entries)[number];
export type JournalImage = { src: string; alt: string; w: number; h: number; caption?: string };
export type JournalEntry = {
  key: string;
  slug: string;
  type: 'Articol Morph' | 'Campanie';
  title: string;
  /** display only: set the part after the colon as a smaller second line, and keep hyphenated words whole */
  titleBreak?: boolean;
  /** publication date (ISO), for Morph articles only; the campaign page carries no date */
  date?: string;
  source: Source['source'];
  excerpt: { voice: 'morph'; text: string };
  /** concept: one line for the index and the article head */
  lede: string;
  /** concept: the verified facts of the source, in order */
  summary: string[];
  /** concept: facts that have changed since the source was written, or that the source leaves out */
  notes: string[];
  lead: JournalImage;
  image?: JournalImage;
  related: { href: string; label: string }[];
};

export const MORPH_BLOG = journal.blog;
const src = (key: string) => journal.entries.find(e => e.key === key)!;
const J1 = src('your-next-form'), J2 = src('workshop-layering'), J3 = src('primitivo');
const J1_SLUG = J1.source.slug!, J2_SLUG = J2.source.slug!;

/** J1: the pre-launch stages as Morph lists them */
export const YNF_STAGES = [
  { dates: '11–13 iulie', names: ['Magnetic', 'Fearless', 'Addictive', 'Euphoric'] },
  { dates: '18–20 iulie', names: ['Untamed', 'Unforgettable', 'Mysterious', 'Desired'] },
  { dates: '25–27 iulie', names: ['Hypnotic', 'Irresistible', 'Reckless', 'Limitless'] },
];

/** J3: Morph's own lines about Primitivo, from the product page */
export const PRIMITIVO_MORPH = { closing: J3.closing!.text, credit: J3.credit!.text };

export const ENTRIES: JournalEntry[] = [
  {
    key: J1.key, slug: J1_SLUG, type: 'Articol Morph', title: J1.source.title!, date: J1.source.published,
    source: J1.source, excerpt: { voice: 'morph', text: J1.excerpt.text },
    lede: 'Articolul cu care Morph a anunțat Your Next Form, colecția dedicată layering-ului.',
    summary: [
      'Your Next Form reunește 12 combinații de layering. Fiecare poartă numele unei identități.',
      'Morph a dezvăluit colecția în trei weekenduri de pre-lansare, câte patru identități o dată.',
      'În aceste weekenduri, la o comandă online de parfum Morph de 100 ml sau de Limited Edition Set, Morph oferea un set Your Next Form, în limita stocului.',
      'Lansarea oficială: 1 august 2026.',
    ],
    notes: ['Oferta de pre-lansare s-a încheiat pe 27 iulie 2026.', 'Colecția e disponibilă din 1 august 2026.'],
    lead: { src: '/morph/campaign/ynf-lead.avif', w: 1920, h: 1353, alt: 'Cutii Your Next Form albe, cu numele identităților pe ele: Unforgettable, Mysterious, Addictive, Fearless', caption: 'Imaginea Morph a articolului.' },
    related: [{ href: '/layering/your-next-form', label: 'Cele 12 seturi Your Next Form' }, { href: `/jurnal/${J2_SLUG}`, label: 'Primul workshop Morph dedicat layering-ului' }],
  },
  {
    key: J2.key, slug: J2_SLUG, type: 'Articol Morph', title: J2.source.title!, titleBreak: true, date: J2.source.published,
    source: J2.source, excerpt: { voice: 'morph', text: J2.excerpt.text },
    lede: 'Articolul Morph despre primul workshop dedicat colecției Your Next Form, ținut înainte de lansare.',
    summary: [
      'Invitații au fost legați la ochi și au mirosit unul dintre cele 12 layering-uri, fără să vadă flaconul sau numele.',
      'Apoi au încercat să-l recreeze: au testat, au comparat și au schimbat ordinea în care aplicau parfumurile.',
      'Numele identităților le-au aflat abia la final.',
    ],
    notes: ['Morph nu publică data, locul sau numărul invitaților.', 'Colecția e disponibilă din 1 august 2026.'],
    lead: { src: '/morph/campaign/workshop-4.avif', w: 1000, h: 705, alt: 'O mână ține o cutie Your Next Form deschisă, cu două flacoane Morph înăuntru', caption: 'Imagine Morph din articol.' },
    related: [{ href: '/layering/your-next-form', label: 'Cele 12 seturi Your Next Form' }, { href: `/jurnal/${J1_SLUG}`, label: 'Your Next Form: noua colecție' }],
  },
  {
    key: J3.key, slug: 'primitivo', type: 'Campanie', title: 'Primitivo',
    source: J3.source, excerpt: { voice: 'morph', text: J3.excerpt.text },
    lede: 'Pagină a conceptului, din imaginile și textele Morph despre Primitivo. Nu e un articol Morph.',
    summary: [],
    notes: [],
    lead: { src: '/morph/campaign/primitivo-rocks.avif', w: 1920, h: 1080, alt: 'Sticla Primitivo, prinsă înclinat între două roci', caption: 'Imagine Morph asociată parfumului Primitivo.' },
    image: {
      src: '/morph/campaign/primitivo-rig.avif', w: 1920, h: 1080,
      alt: 'Mâini în mănuși de laborator pe o structură de metal: una lasă să curgă nisip, altele țin lemn, un bloc închis la culoare, o fâșie de testare și sticla Primitivo',
      caption: 'Imagine Morph asociată parfumului Primitivo. Un decupaj din același cadru e imaginea colecției Ice.',
    },
    related: [{ href: '/parfumuri/ice', label: 'Colecția Ice' }],
  },
];

/** where a Journal image comes from in Morph's media library (data/assets.json) */
export const imageSource = (src: string) => {
  const a = assets.assets.find(x => src.endsWith('/' + x.file));
  return a && a.status === 'concept' ? assets.base + a.src : null;
};

export const bySlug = (slug: string) => ENTRIES.find(e => e.slug === slug) ?? null;
export const journalHref = (key: string) => `/jurnal/${ENTRIES.find(e => e.key === key)!.slug}`;
export const longDate = (iso: string) => new Date(`${iso}T12:00:00Z`).toLocaleDateString('ro-RO', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' });
