// Journal sources (docs/design/phase-c4-1b-journal.md). Writes data/journal.json: for each entry, the source's metadata
// and the short Morph passages the concept quotes, never a full article body. J1 and J2 are read from Morph's
// WordPress API (two posts, nothing else); J3 quotes the Primitivo product text already in data/catalog.json.
// Each excerpt is chosen by position (paragraph, sentences) and stored verbatim. Usage: npm run journal
import { readFileSync, writeFileSync } from 'fs';
import path from 'path';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const API = 'https://morphparfum.ro/wp-json/wp/v2/posts/';

// paragraph index (0-based, in document order) and a sentence range [from, to) within it
const POSTS = [
  { key: 'your-next-form', id: 43913, excerpt: { p: 2, s: [1, 5] } },
  { key: 'workshop-layering', id: 43904, excerpt: { p: 3, s: [1, 3] } },
];

const decode = t => t
  .replace(/<[^>]+>/g, '')
  .replace(/&#(\d+);/g, (_, n) => String.fromCodePoint(+n))
  .replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&#8211;/g, '–')
  .replace(/\s+/g, ' ').trim();
const paragraphs = html => [...html.matchAll(/<p[^>]*>([\s\S]*?)<\/p>/g)].map(m => decode(m[1])).filter(Boolean);
const sentences = t => t.match(/[^.!?]+[.!?]+/g).map(x => x.trim());
const pick = (paras, { p, s }) => sentences(paras[p]).slice(...s).join(' ');

const entries = [];
for (const { key, id, excerpt } of POSTS) {
  const api = `${API}${id}?_fields=id,date,modified,slug,link,title,content`;
  const r = await fetch(api);
  if (!r.ok) throw new Error(`${r.status} ${api}`);
  const post = await r.json();
  entries.push({
    key,
    source: {
      kind: 'morph-article',
      postId: post.id,
      url: post.link,
      api: `${API}${id}`,
      slug: post.slug,
      title: decode(post.title.rendered),
      published: post.date.slice(0, 10),
      modified: post.modified.slice(0, 10),
    },
    excerpt: { voice: 'morph', text: pick(paragraphs(post.content.rendered), excerpt), at: excerpt },
  });
}

// J3: Morph's product text for Primitivo, from the Store API snapshot (npm run snapshot)
const catalog = JSON.parse(readFileSync(path.join(root, 'data/catalog.json'), 'utf8'));
const primitivo = catalog.perfumes.find(p => p.slug === 'morph-primitivo-eau-de-parfum-unisex');
const desc = primitivo.sections.find(x => /^Descriere/.test(x.heading)).body.split('\n');
const credit = sentences(primitivo.summary)[0].match(/creat de [^,]+/)[0];
const closing = sentences(desc.at(-1)).at(-1);
entries.push({
  key: 'primitivo',
  source: {
    kind: 'morph-product',
    productId: primitivo.id,
    url: primitivo.url,
    api: `https://morphparfum.ro/wp-json/wc/store/v1/products?slug=${primitivo.slug}`,
    snapshot: catalog.snapshotAt.slice(0, 10),
  },
  excerpt: { voice: 'morph', text: desc[0], at: 'description, paragraph 1' },
  closing: { voice: 'morph', text: closing, at: 'description, last sentence' },
  credit: { voice: 'morph', text: credit, at: 'summary, sentence 1' },
});

const out = {
  note: 'Morph wording quoted by the Journal, with its source. Generated by `npm run journal`; do not edit by hand. Only metadata and short excerpts are stored: the full articles stay on morphparfum.ro. Concept-written copy lives in lib/journal.ts.',
  blog: 'https://morphparfum.ro/blog/',
  entries,
};
writeFileSync(path.join(root, 'data/journal.json'), JSON.stringify(out, null, 2) + '\n');
for (const e of entries) console.log(`${e.key.padEnd(18)} ${e.excerpt.text.slice(0, 70)}…`);
